import express from 'express';
import cors from 'cors';
import authRoutes from './routes/auth.routes.js';
import productRoutes from './routes/product.routes.js';
import collectionRoutes from './routes/collection.routes.js';
import assortmentRoutes from './routes/assortment.routes.js';
import colorRoutes from './routes/color.routes.js';
import orderRoutes from './routes/order.routes.js';
import { checkHealth } from './controllers/healthController.js';
import { getSetting, updateSetting } from './controllers/settingsController.js';
const app = express();
app.use(cors());
app.use(express.json());
app.get('/api/health', checkHealth);
app.use('/api/auth', authRoutes);
app.use('/api/products', productRoutes);
app.use('/api/collections', collectionRoutes);
app.use('/api/assortments', assortmentRoutes);
app.use('/api/colors', colorRoutes);
app.use('/api/orders', orderRoutes);
app.get('/api/settings/:key', getSetting);
app.put('/api/settings/:key', updateSetting);
app.get('/api', (_req, res) => {
    res.json({ status: 'API OK' });
});
export default app;
